Append node types countAction, goalAction, trendAction
SC-Networks/campaign-schema pull request #9
Opened 2023-05-24 15:37 UTC by cougargit

2023-05-24 18:59 UTC, l-x approved these changes

2023-05-24 19:52 UTC, l-x requested changes
Bitte den PR nochmal gegen develop rebasen, da gibt es Änderungen <- hat sich erledigt

2023-05-24 19:56 UTC, l-x approved these changes

2023-05-25 09:19 UTC, gaggala reviewed
Die neuen Knoten lösen keine Aktion aus, daher sind sie nicht unter "actions" anzusiedeln. Laut Ticket soll es ebenfalls eine neue Gruppe von Knoten sein. Entsprechend würde ich eine neue Gruppe "indicators" vorschlagen.

2023-05-25 10:03 UTC, gaggala commented on schema.json
> +                "date": {
Das Propertynaming ist problematisch, "date" ist ein reservierter Begriff. Treffender für die Beschreibung der property im Sinne des Features wäre "startDate".

2023-05-25 10:03 UTC, gaggala commented on schema.json
> +        "goalAction": {
"targetIndicator" wäre die im Englischen korrekte Bezeichnung.

2023-05-25 10:03 UTC, gaggala commented on schema.json
> +                    {
Das ist kein valides json-Schema. Alle weiteren Stellen, an welchen Objekte stehen, sind auch zu korrigieren.

```javascript
{
    "type": "object",
    "properties": {
        "type": {
            "const": "dateTime"
        },
        "value": {
            "$ref": "#/definitions/types/dateTime"
        }
    },
    "required": [
        "type",
        "value"
    ],
    "additionalProperties": false
}
```

2023-05-25 10:03 UTC, gaggala commented on schema.json
> +                "goal": {
passend zum vorgeschlagenen Knotennamen, wäre diese property in "target" umzubenennen.

2023-05-25 10:03 UTC, gaggala commented on schema.json
> +                "period": {
naming ist sehr irreführend, es handelt sich in dem zugehörigen oneOf einmal um einen Zeitpunkt und einmal um eine Zeitspanne. Konsistent zum "countIndicator" wäre hier ebenfalls "startDate" das richtige property naming.

2023-05-25 10:50 UTC, gaggala commented on schema.json
> +            "config": {
Die config ist nicht ausreichend. Laut Ticket ist auch der [Zieltyp] und die [WertDarstellung] einstellbar.

2023-05-25 12:35 UTC, closed without merging